apiVersion: v1
kind: Secret
metadata:
  name: rag-app-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded OpenAI API key
  # To create: echo -n "your-openai-api-key" | base64
  OPENAI_API_KEY: ""  # Replace with base64 encoded API key