apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-app
  namespace: default
  labels:
    app: rag-app
spec:
  replicas: 1  # Reduced for local development
  selector:
    matchLabels:
      app: rag-app
  template:
    metadata:
      labels:
        app: rag-app
    spec:
      containers:
      - name: rag-app
        image: rag-app:latest  # Local image for Minikube
        imagePullPolicy: Never  # Use local images
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: rag-app-secrets
              key: OPENAI_API_KEY
        envFrom:
        - configMapRef:
            name: rag-app-config
        resources:
          requests:
            memory: "256Mi"  # Reduced for local development
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: chroma-storage
          mountPath: /app/chroma_db
        - name: data-storage
          mountPath: /app/data
      volumes:
      - name: chroma-storage
        persistentVolumeClaim:
          claimName: chroma-pvc
      - name: data-storage
        persistentVolumeClaim:
          claimName: data-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Minikube default storage class
  resources:
    requests:
      storage: 2Gi  # Reduced for local development

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Minikube default storage class
  resources:
    requests:
      storage: 1Gi  # Reduced for local development