apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-frontend
  labels:
    app: streamlit-frontend
    tier: frontend
spec:
  replicas: 1  # Reduced for local development
  selector:
    matchLabels:
      app: streamlit-frontend
  template:
    metadata:
      labels:
        app: streamlit-frontend
        tier: frontend
    spec:
      containers:
      - name: streamlit-frontend
        image: rag-streamlit:latest  # Local image for Minikube
        imagePullPolicy: Never  # Use local images
        ports:
        - containerPort: 8501
        env:
        - name: API_BASE_URL
          value: "http://rag-app-service:8000"
        resources:
          requests:
            memory: "128Mi"  # Reduced for local development
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false